Repository DEFRA/water-abstraction-acceptance-tests, pull requests merged in 2023-07, with the labels that each got.

#59 Add supp. billing scenario change account
  cypress/e2e/internal/billing/scenarios/change-billing-acount-current-year.cy.js
Labels: enhancement

#61 Add supplementary billing scenario to change account in previous financial year
  cypress/e2e/internal/billing/scenarios/change-billing-account-current-year.cy.js
  cypress/e2e/internal/billing/scenarios/change-billing-account-previous-year.cy.js
Labels: enhancement

#62 Fix `cancel-existing` test
  cypress/e2e/internal/billing/supplementary/cancel-existing.cy.js
Labels: bug

#65 Move tests to `supplementary` folder
  cypress/e2e/internal/billing/supplementary/change-billing-account-current-year.cy.js
  cypress/e2e/internal/billing/supplementary/change-billing-account-previous-year.cy.js
  cypress/e2e/internal/billing/supplementary/non-charge-licence-credit.cy.js
Labels: housekeeping

#66 Add SROC Supplementary billing acceptance tests
  cypress/e2e/internal/billing/supplementary/replace-cv-2023-fin-year-no-changes.cy.js
  cypress/e2e/internal/billing/supplementary/replace-cv-current-year-with-changes.cy.js
Labels: enhancement

#67 Add SROC supplementary reissuing tests
  cypress/e2e/internal/billing/supplementary/reissue-presroc.cy.js
  cypress/e2e/internal/billing/supplementary/reissue-sroc.cy.js
Labels: enhancement
