Repository DEFRA/water-abstraction-acceptance-tests, pull requests merged in 2024-07, with the labels that each got.

#88 No returns required journey acceptance tests
  cypress/e2e/internal/returns-requirements/no-returns-required.cy.js
Labels: enhancement

#96 Return required (abstraction data) acceptance test
  cypress/e2e/internal/returns-requirements/abstraction-data.cy.js
  cypress/fixtures/generate-using-abstraction-data.json
Labels: enhancement

#120 Update acceptance tests to new view licence page
  cypress/e2e/internal/billing/supplementary/change-billing-account-current-year.cy.js
  cypress/e2e/internal/billing/supplementary/change-billing-account-previous-year.cy.js
  cypress/e2e/internal/billing/supplementary/non-charge-licence-credit.cy.js
  cypress/e2e/internal/billing/supplementary/replace-cv-2023-fin-year-no-changes.cy.js
  cypress/e2e/internal/billing/supplementary/replace-cv-current-year-with-changes.cy.js
  cypress/e2e/internal/charge-information/presroc/licence-transfer.cy.js
  cypress/e2e/internal/charge-information/sroc/journey.cy.js
  cypress/e2e/internal/charge-information/sroc/validation.cy.js
  cypress/e2e/internal/licence-agreements/delete-licence-agreement.cy.js
  cypress/e2e/internal/licence-agreements/end-licence-agreement.cy.js
  cypress/e2e/internal/licence-agreements/new-licence-agreement.cy.js
  cypress/e2e/internal/returns-requirements/abstraction-data.cy.js
  cypress/e2e/internal/returns-requirements/cancel-returns.cy.js
  cypress/e2e/internal/returns-requirements/copy-existing.cy.js
  cypress/e2e/internal/returns-requirements/no-returns-required.cy.js
  cypress/e2e/internal/returns-requirements/returns-required.cy.js
  cypress/e2e/internal/user/permissions/billing-and-data.cy.js
  cypress/e2e/internal/user/permissions/psc.cy.js
Labels: housekeeping, testing

#121 Fix failing requirement due to new reasons added
  cypress/e2e/internal/returns-requirements/abstraction-data.cy.js
  cypress/e2e/internal/returns-requirements/cancel-returns.cy.js
  cypress/e2e/internal/returns-requirements/copy-existing.cy.js
  cypress/e2e/internal/returns-requirements/returns-required.cy.js
Labels: housekeeping

#122 Update two-part tariff acceptance tests
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-01.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-02.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-03.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-04.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-05.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-06.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-07.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-08.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-09.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-11.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-12.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-13.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-14.cy.js
  cypress/fixtures/review-scenario-14.json
Labels: enhancement

#123 Update return requirement tests 4 purpose changes
  cypress/e2e/internal/returns-requirements/abstraction-data.cy.js
  cypress/e2e/internal/returns-requirements/cancel-returns.cy.js
  cypress/e2e/internal/returns-requirements/copy-existing.cy.js
  cypress/e2e/internal/returns-requirements/returns-required.cy.js
Labels: housekeeping

#124 Update two-part tariff acceptance tests
  cypress/e2e/internal/billing/two-part-tariff/review/README.md
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-01.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-02.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-03.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-04.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-05.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-06.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-07.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-08.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-09.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-10.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-11.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-12.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-13.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-14.cy.js
  cypress/e2e/internal/billing/two-part-tariff/scenario-one.cy.js
Labels: enhancement
