Repository DEFRA/water-abstraction-acceptance-tests, pull requests merged in 2024-08, with the labels that each got.

#125 Replace two part tariff test data
  cypress/e2e/internal/billing/two-part-tariff/cancel-existing.cy.js
  cypress/e2e/internal/billing/two-part-tariff/journey.cy.js
  cypress/fixtures/pre-sroc-two-part-tariff-bill-run.json
  cypress/fixtures/two-part-tariff-cancel-existing.json
Labels: enhancement

#126 Replace notify mock data
  cypress/e2e/external/notify-callback.cy.js
  cypress/fixtures/notify-mock-notification.json
Labels: enhancement

#119 Switch remaining acceptance tests to use new data loader
  cypress/e2e/external/licence-alias-naming.cy.js
  cypress/e2e/external/login/journey.cy.js
  cypress/e2e/external/registration/journey.cy.js
  cypress/e2e/external/registration/validation.cy.js
  cypress/e2e/external/reset-password/journey.cy.js
  cypress/e2e/external/returns/metered-readings-return.cy.js
  cypress/e2e/external/returns/null-return.cy.js
  cypress/e2e/external/returns/volumes-gallons-return.cy.js
  cypress/e2e/external/returns/volumes-litres-return.cy.js
  cypress/e2e/external/returns/volumes-megalitres-return.cy.js
  cypress/e2e/external/sharing-access-with-existing-user.cy.js
  cypress/e2e/external/sharing-access-with-new-user.cy.js
  cypress/e2e/external/view-licences.cy.js
  cypress/e2e/external/view-returns.cy.js
  cypress/e2e/internal/abstraction-alerts/journey.cy.js
  cypress/e2e/internal/abstraction-alerts/validation.cy.js
  cypress/e2e/internal/address-entry/journey.cy.js
  cypress/e2e/internal/address-entry/validation.cy.js
  cypress/e2e/internal/charge-information/presroc/licence-transfer.cy.js
  cypress/e2e/internal/charge-information/sroc/journey.cy.js
  cypress/e2e/internal/charge-information/sroc/validation.cy.js
  cypress/e2e/internal/licence-agreements/delete-licence-agreement.cy.js
  cypress/e2e/internal/licence-agreements/end-licence-agreement.cy.js
  cypress/e2e/internal/licence-agreements/new-licence-agreement.cy.js
  cypress/e2e/internal/licence/search.cy.js
  cypress/e2e/internal/licence/view-contacts.cy.js
  cypress/e2e/internal/paper-returns/journey.cy.js
  cypress/e2e/internal/paper-returns/validation.cy.js
  cypress/e2e/internal/reset-password/journey.cy.js
  cypress/e2e/internal/returns-requirements/no-returns-required.cy.js
  cypress/e2e/internal/returns/record-receipt.cy.js
  cypress/e2e/internal/returns/send-invite.cy.js
  cypress/e2e/internal/returns/send-reminder.cy.js
  cypress/e2e/internal/returns/submit.cy.js
  cypress/e2e/internal/returns/view-status.cy.js
  cypress/e2e/internal/user/change-permissions.cy.js
  cypress/e2e/internal/user/create-user.cy.js
  cypress/e2e/internal/user/login-logout.cy.js
  cypress/e2e/internal/user/permissions/billing-and-data.cy.js
  cypress/e2e/internal/user/permissions/psc.cy.js
  cypress/e2e/internal/workflow/remove-charge-information.cy.js
  cypress/fixtures/barebones.json
  cypress/fixtures/charge-version-workflow.json
  cypress/fixtures/users.json
Labels: housekeeping

#127 Delete bulk-upload acceptance test
  cypress/e2e/external/bulk-upload.cy.js
Labels: housekeeping

#129 Replace loaded region with seeded ones
  cypress/e2e/internal/billing/two-part-tariff/cancel-existing.cy.js
  cypress/e2e/internal/billing/two-part-tariff/empty-bill-run.cy.js
  cypress/fixtures/barebones.json
  cypress/fixtures/generate-using-abstraction-data.json
  cypress/fixtures/pre-sroc-two-part-tariff-bill-run.json
  cypress/fixtures/returns-requirements.json
  cypress/fixtures/review-scenario-licence.json
  cypress/fixtures/sroc-billing.json
  cypress/fixtures/sroc-two-part-tariff-simple-licence-data.json
  cypress/fixtures/sroc-two-part-tariff.json
  cypress/fixtures/two-part-tariff-cancel-existing.json
Labels: housekeeping

#130 Fix Return Requirements fixtures file
  cypress/fixtures/returns-requirements.json
Labels: bug

#131 Add external user change email test
  cypress/e2e/external/change-email/journey.cy.js
  cypress/fixtures/change-email-user.json
Labels: enhancement
