Repository DEFRA/water-abstraction-acceptance-tests, pull requests merged in 2024-06, with the labels that each got.

#92 Scenario one for the two-part tariff review pages
  cypress/e2e/internal/billing/two-part-tariff/empty-bill-run.cy.js
  cypress/e2e/internal/billing/two-part-tariff/scenario-one.cy.js
  cypress/fixtures/sroc-two-part-tariff-scenario-one-data.json
  cypress/fixtures/sroc-two-part-tariff.json
Labels: enhancement

#95 Altering two-part tariff scenario one fixtures
  cypress/fixtures/sroc-two-part-tariff-scenario-one-data.json
Labels: bug

#91 Returns required journey acceptance tests
  cypress/e2e/internal/returns-requirements/returns-required.cy.js
  cypress/fixtures/returns-requirements.json
Labels: enhancement

#97 Updating testing scenario one for two-part tariff review pages
  cypress/e2e/internal/billing/two-part-tariff/scenario-one.cy.js
Labels: enhancement

#100 Fix two-part tariff scenario one
  cypress/e2e/internal/billing/two-part-tariff/scenario-one.cy.js
Labels: bug

#93 Scenario two for the two-part tariff review pages
  cypress/e2e/internal/billing/two-part-tariff/scenario-one.cy.js
  cypress/e2e/internal/billing/two-part-tariff/scenario-two.cy.js
  cypress/fixtures/sroc-two-part-tariff-scenario-two-data.json
  cypress/fixtures/sroc-two-part-tariff-simple-licence-data.json
Labels: enhancement

#99 Scenario three the two-part tariff review pages
  cypress/e2e/internal/billing/two-part-tariff/scenario-three.cy.js
Labels: enhancement

#101 Scenario four for the two-part tariff review pages
  cypress/e2e/internal/billing/two-part-tariff/scenario-four.cy.js
Labels: enhancement

#94 Add cancel a return requirement acceptance test
  cypress/e2e/internal/returns-requirements/cancel-returns.cy.js
Labels: enhancement

#103 Scenario six for the two-part tariff review pages
  cypress/e2e/internal/billing/two-part-tariff/scenario-six.cy.js
Labels: enhancement

#104 Scenario Seven for the two-part tariff review pages
  cypress/e2e/internal/billing/two-part-tariff/scenario-seven.cy.js
Labels: enhancement

#105 Scenario Eight for the two-part tariff review pages
  cypress/e2e/internal/billing/two-part-tariff/scenario-eight.cy.js
Labels: enhancement

#107 Fixing broken two-part tariff acceptance tests
  cypress/e2e/internal/billing/two-part-tariff/scenario-eight.cy.js
  cypress/e2e/internal/billing/two-part-tariff/scenario-five.cy.js
  cypress/e2e/internal/billing/two-part-tariff/scenario-four.cy.js
  cypress/e2e/internal/billing/two-part-tariff/scenario-one.cy.js
  cypress/e2e/internal/billing/two-part-tariff/scenario-seven.cy.js
  cypress/e2e/internal/billing/two-part-tariff/scenario-six.cy.js
  cypress/e2e/internal/billing/two-part-tariff/scenario-three.cy.js
  cypress/e2e/internal/billing/two-part-tariff/scenario-two.cy.js
Labels: bug

#106 Scenario Nine for the two-part tariff review pages
  cypress/e2e/internal/billing/two-part-tariff/scenario-nine.cy.js
  cypress/fixtures/sroc-two-part-tariff-scenario-nine.json
Labels: enhancement

#109 Fix two-part tariff scenario nine
  cypress/fixtures/sroc-two-part-tariff-scenario-nine.json
Labels: bug

#111 Fix ret. req. tests after changes to main
  cypress/e2e/internal/returns-requirements/cancel-returns.cy.js
  cypress/e2e/internal/returns-requirements/returns-required.cy.js
  cypress/fixtures/returns-requirements.json
Labels: bug

#108 Scenario Ten for the two-part tariff review pages
  cypress/e2e/internal/billing/two-part-tariff/scenario-ten.cy.js
Labels: enhancement

#114 Scenario Fourteen for the two-part tariff review pages
  cypress/e2e/internal/billing/two-part-tariff/scenario-fourteen.cy.js
  cypress/fixtures/sroc-two-part-tariff-scenario-fourteen-data.json
Labels: enhancement

#113 Scenario Thirteen for the two-part tariff review pages
  cypress/e2e/internal/billing/two-part-tariff/scenario-thirteen.cy.js
Labels: enhancement

#112 Scenario Twelve for the two-part tariff review pages
  cypress/e2e/internal/billing/two-part-tariff/scenario-twelve.cy.js
  cypress/fixtures/sroc-two-part-tariff-scenario-twelve-data.json
Labels: enhancement

#115 Fix two-part tariff scenario one acceptance test
  cypress/e2e/internal/billing/two-part-tariff/scenario-one.cy.js
Labels: bug

#116 Two-part tariff test scenarios housekeeping
  cypress/e2e/internal/billing/two-part-tariff/review/README.md
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-eight.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-eleven.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-five.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-four.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-fourteen.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-nine.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-one.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-seven.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-six.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-ten.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-thirteen.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-three.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-twelve.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-two.cy.js
Labels: housekeeping

#117 Fix non-working billing tests
  cypress/e2e/internal/billing/supplementary/change-billing-account-current-year.cy.js
  cypress/e2e/internal/billing/supplementary/change-billing-account-previous-year.cy.js
  cypress/e2e/internal/billing/supplementary/non-charge-licence-credit.cy.js
  cypress/e2e/internal/billing/supplementary/replace-cv-2023-fin-year-no-changes.cy.js
  cypress/e2e/internal/billing/supplementary/replace-cv-current-year-with-changes.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-one.cy.js
  cypress/fixtures/sroc-billing.json
Labels: bug

#98 Add return required (copy from existing) test
  cypress/e2e/internal/returns-requirements/copy-existing.cy.js
  cypress/fixtures/returns-requirements.json
Labels: enhancement

#118 Fix 2PT fixture data
  cypress/e2e/internal/billing/two-part-tariff/review/README.md
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-01.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-02.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-03.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-04.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-05.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-06.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-07.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-08.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-09.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-10.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-11.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-12.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-13.cy.js
  cypress/e2e/internal/billing/two-part-tariff/review/scenario-14.cy.js
  cypress/fixtures/review-scenario-01.json
  cypress/fixtures/review-scenario-02.json
  cypress/fixtures/review-scenario-03.json
  cypress/fixtures/review-scenario-04.json
  cypress/fixtures/review-scenario-05.json
  cypress/fixtures/review-scenario-06.json
  cypress/fixtures/review-scenario-07.json
  cypress/fixtures/review-scenario-08.json
  cypress/fixtures/review-scenario-09.json
  cypress/fixtures/review-scenario-10.json
  cypress/fixtures/review-scenario-11.json
  cypress/fixtures/review-scenario-12.json
  cypress/fixtures/review-scenario-13.json
  cypress/fixtures/review-scenario-14.json
  cypress/fixtures/review-scenario-licence.json
  cypress/fixtures/sroc-two-part-tariff-scenario-eleven-data.json
  cypress/fixtures/sroc-two-part-tariff-scenario-fourteen-data.json
  cypress/fixtures/sroc-two-part-tariff-scenario-twelve-data.json
  cypress/fixtures/sroc-two-part-tariff-scenario-two-data.json
Labels: bug
