Repository DEFRA/water-abstraction-acceptance-tests, pull requests merged in 2025-08, with the labels that each got.

#179 Switch to using Snyk CLI action in CI
  .github/workflows/ci.yml
Labels: housekeeping

#182 Add snyk exception for tmp
  .snyk
Labels: security

#181 Update billing test due to changed charges
  cypress/e2e/internal/billing/supplementary/replace-cv-current-year-with-changes.cy.js
Labels: housekeeping

#188 Update `send-alert` test
  cypress/e2e/internal/monitoring-stations/abstraction-alerts/send-alert.cy.js
Labels: bug
